name: Run GPT4All

on: [push]

jobs:
  gpt4all-job:
    runs-on: ubuntu-latest

    container:
      image: nvidia/cuda:11.0-base

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install gpt4all

    - name: Run GPT4All script
      run: python run_gpt4all.py