name: Run Haystack

on: [push]

jobs:
  haystack-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch
        pip install farm-haystack[inference]

    - name: Run Haystack script
      run: python run_haystack.py